### ISSUE TITLE
Investigate possibility of replacing the shroud/fog vision system

### ISSUE THREAD

**Issue by obrakmann** [obrakmann/openra-wargame#1]
The replacement should look something like this on the YAML side:

```yaml
rifle_infantry:
    Visible:
        Silhouette: Small
    Vision:
        RangeAgainst:
            Small: 5c0
            Large: 10c0
            Aircraft: 20c0

leopard2:
    Visible:
        Silhouette: Large

f15:
    Visible:
        Silhouette: Aircraft
```

This may not actually not be possible without major surgery to the core mod code if the existence of a shroud is too hardcoded.
